project:
  type: website
  output-dir: docs

website:
  google-analytics: "G-Y4BPJM0CQX"
  title: "Dmytro's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ducha-aiki
      - icon: twitter
        href: https://x.com/ducha_aiki
format:
  html:
    theme: cosmo
    css: styles.css



